name: Test Workflow Run Trigger 

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed
      
jobs:
  log-result:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Log Success 
        run: echo "Success"
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Log Faliure 
        run: echo "Faliure"
