name: Test Workflow Run Trigger 

on:
  workflow_run:
    workflows:
      - Deploy Content to cicd-test-la \[38f74bbf-7e5c-4cf0-93cd-674d920273ba\]
    types:
      - completed
      
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Log Success 
        run: echo "Success"
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Log Faliure 
        run: echo "Faliure"
