name: Send Status if Workflow Failed 

on:
  workflow_run:
    workflows:
      - Deploy Content to *
    types:
      - completed
      
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send Teams Message if failed
        uses: jdcargile/ms-teams-notification@v1.3
        if: ${{ always() && github.event.workflow_run.conclusion == 'failure' }}
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Workflow Run Failed On GitHub - ${{ github.event.workflow_run.html_url }}
          notification-color: dc3545 
