name: Test Workflow Run Trigger 

on:
  workflow_run:
    workflows:
      - Deploy Content to cicd-test-la \[38f74bbf-7e5c-4cf0-93cd-674d920273ba\]
    types:
      - completed
      
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send Teams Message if failed
        uses: jdcargile/ms-teams-notification@v1.3
        if: ${{ always() && github.event.workflow_run.conclusion == 'failure' }}
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Workflow Run Failed On GitHub. [View Workflow Run](${{ github.event.workflow.html_url }})
          notification-color: dc3545 
